#!/bin/bash
# daily cleanup script

# reload nginx to prevent file lock and immediately clear cache
nginx -s reload

# delete anything older than 2 days
find /tmp/nginx/* -type f -mtime +1 -exec rm -f {} \;
find /var/cache/nginx/* -type f -mtime +1 -exec rm -f {} \;
